name: MCEconomy
version: '${version}'
main: leehj050211.mceconomy.MCEconomy
api-version: '1.20'
commands:
  메뉴:
    description: 메뉴를 엽니다.
    usage: /메뉴
  송금:
    description: 상대방에게 돈을 보낼 수 있습니다.
    usage: /송금 <상대방 닉네임> <금액>
  상점:
    description: 상점에서 여러 상품을 살 수 있습니다.
    usage: /상점
  가챠:
    description: 가챠 상점에서 가챠를 돌릴 수 있습니다.
    usage: /가챠
  작업장:
    description: 일을 할 수 있는 작업장으로 이동합니다.
    usage: /작업장
  부동산위치:
    description: 현재 위치를 기준으로 구매할 부동산의 범위를 정합니다.
    usage: /부동산위치 <1 또는 2>
  부동산구매:
    description: 부동산을 구매할 수 있습니다.
    usage: /부동산구매
