name: MCEconomy
version: '${version}'
main: leehj050211.mceconomy.MCEconomy
api-version: '1.20'
commands:
  메뉴:
    description: 메뉴를 엽니다.
    usage: /메뉴
  송금:
    description: 상대방에게 돈을 보낼 수 있습니다.
    usage: /송금 <상대방 닉네임> <금액>
  상점:
    description: 상점에서 여러 상품을 살 수 있습니다.
    usage: /상점
  작업장:
    description: 일을 할 수 있는 작업장으로 이동합니다.
    usage: /작업장
