name: MCEconomy
version: '${version}'
main: leehj050211.mceconomy.MCEconomy
api-version: '1.20'
commands:
  송금:
    description: 상대방에게 돈을 보낼 수 있습니다.
    usage: /송금 <상대방 닉네임> <금액>
  상점:
    description: 상점에서 여러 상품을 살 수 있습니다.
    usage: /상점
  가챠:
    description: 가챠 상점에서 가챠를 돌릴 수 있습니다.
    usage: /가챠